#!/bin/bash
echo "🔒 Digite o token do SonarQube (não será salvo):"
read -s SONAR_TOKEN

echo "🚀 Rodando análise SonarQube..."
mvn clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN

if [ $? -ne 0 ]; then
  echo "❌ Falha na análise Sonar. Commit cancelado."
  exit 1
else
  echo "✅ Análise Sonar concluída com sucesso."
fi
